<?php

namespace App\Filament\Resources\FinancialReleasesResource\Pages;

use App\Filament\Resources\FinancialReleasesResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateFinancialReleases extends CreateRecord
{
    protected static string $resource = FinancialReleasesResource::class;

    public function getCreatedNotificationMessage(): ?string
    {
        return 'Lançamento criado.'; // TODO: Change the autogenerated stub
    }
}
